export { default as Navbar } from './navbar/Navbar'
export { default as Footer } from './footer/Footer'
export { default as MinimalFooter } from './footer/MinimalFooter'
export { default as Jumbotron } from './jumbotron/Jumbotron'
export { default as Banner} from './banner/Banner'
