export { default as Navbar } from './navbar/Navbar'
export { default as Footer } from './footer/Footer'
export { default as MinimalFooter } from './footer/MinimalFooter'
export { default as Jumbotron } from './jumbotron/Jumbotron'
export { default as CategoryCard } from './category-card/CategoryCard'
export { default as TestimonialCard } from './testimonial-card/TestimonialCard'
export { default as CtaSection } from './cta-section/CtaSection'
